image: gcc

stages:          # List of stages for jobs, and their order of execution
  - build

build:
  stage: build

  before_script:
    - |
      if [ ! -d ../googletest ]; then
        CWD=`pwd`
        cd ..
        git clone https://github.com/google/googletest
        apt update
        apt-get install -y cmake
        apt-get install -y curl
        cd $CWD
      fi

  script:
    - cmake .
    - make

