image: gcc

stages:          # List of stages for jobs, and their order of execution
  - build

build:
  stage: build

  before_script:
    - |
      if [ ! -d ../googletest ]; then
        CWD=`pwd`
        cd ..
        git clone https://github.com/google/googletest
        apt update
        apt install libcurl4-gnutls-dev
        apt install libcurl4-openssl-dev
        apt install libcurl4-nss-dev
        cd $CWD
      fi

  script:
    - make

